
/**********
<company="Mobilize.Net">
    Copyright (C) Mobilize.Net info@mobilize.net - All Rights Reserved
    This file is part of the Mobilize Frameworks, which is
    proprietary and confidential.
    NOTICE:  All information contained herein is, and remains
    the property of Mobilize.Net Corporation.
    The intellectual and technical concepts contained herein are
    proprietary to Mobilize.Net Corporation and may be covered
    by U.S. Patents, and are protected by trade secret or copyright law.
    Dissemination of this information or reproduction of this material
    is strictly forbidden unless prior written permission is obtained
    from Mobilize.Net Corporation.
</copyright>
**********/

-----------
-- Set Table with unique datatypes.
-----------
CREATE SET TABLE SALES.DimSalesOverview,
	NO FALLBACK,
	NO BEFORE JOURNAL,
	NO AFTER JOURNAL,
	CHECKSUM = DEFAULT,
	DEFAULT MERGEBLOCKRATIO
	(
		EmployeeKey INTEGER NOT NULL,
		ParentEmployeeKey INTEGER,
		EmployeeNationalIDAlternateKey VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
		FirstName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
		NameStyle BYTEINT CHECK ( NameStyle  IN (0 ,1 ) ) NOT NULL,
		"Title" VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
		HireDate DATE FORMAT 'yyyy-mm-dd',
		PayFrequency BYTEINT,
		BaseRate NUMBER(18,4),
		VacationHours SMALLINT,
		EmployeePhoto BLOB(2097088000),
		Weight NUMBER,
		SalesOrderLineNumber SMALLINT NOT NULL COMPRESS (1 ,2 ,3 ),
		SalesReasonKey INTEGER NOT NULL COMPRESS (1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ),
		EmailAddress VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS USING TD_SYSFNLIB.TRANSUNICODETOUTF8 DECOMPRESS USING TD_SYSFNLIB.TRANSUTF8TOUNICODE,
		EnglishEducation VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Bachelors','Partial College','High School','Graduate Degree','Partial High School'),
		EMPLOYMENT_PERIOD PERIOD(DATE) FORMAT 'YYYY-MM-DD',
		INTERVAL_YEAR_TYPE INTERVAL YEAR(2),
		INTERVAL_MONTH_TYPE INTERVAL MONTH(2),
		SALARY_AMOUNT DECIMAL(10,2) NOT NULL,
		TS TIMESTAMP(6),
	
PRIMARY KEY ( EmployeeKey ))
;


-----------
-- Set Table.
-----------
CREATE SET TABLE SALES.DimSalesReason ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SalesReasonKey INTEGER NOT NULL,
      SalesReasonAlternateKey INTEGER NOT NULL,
      SalesReasonName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SalesReasonReasonType VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL, 
PRIMARY KEY ( SalesReasonKey ))
;


-----------
-- Table (unspecified).
-----------
CREATE TABLE SALES.FactSalesQuota ,NO FALLBACK ,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO
    (
     SalesQuotaKey INTEGER NOT NULL,
     EmployeeKey INTEGER NOT NULL,
     DateKey INTEGER NOT NULL,
     CalendarYear SMALLINT NOT NULL,
     CalendarQuarter BYTEINT NOT NULL,
     SalesAmountQuota NUMBER(18,4) NOT NULL,
     "Date" DATE FORMAT 'yyyy-mm-dd', 
PRIMARY KEY ( SalesQuotaKey ))
PARTITION BY COLUMN (CALENDARYEAR);
;


-----------
-- Multiset Table.
-----------
CREATE MULTISET TABLE HR.PERSON_EMPLOYMENT_PERIOD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PERSON_ID INTEGER NOT NULL,
      EMPLOYMENT_PERIOD PERIOD(DATE) FORMAT 'YYYY-MM-DD')
PRIMARY INDEX ( PERSON_ID );


---------
-- Volatile Table.
---------
CREATE MULTISET VOLATILE TABLE PRODUCT.TEMP_QUAL_TABLE, NO LOG 
AS 
(
SELECT
YR || '-' || SALE_MONTH (NAMED YEARMONTH),
CALENDARYEAR YR,
MONTHNUMBEROFYEAR AS SALE_MONTH,
SALESAMOUNT AS SALE_AMT
FROM
HR.DIMDATE DD,
SALES.FACTINTERNETSALES FIS
WHERE FIS.ORDERDATEKEY = DD.DATEKEY
QUALIFY RANK() OVER (PARTITION BY YR ORDER BY SALESAMOUNT) = 1
)
WITH DATA
ON COMMIT PRESERVE ROWS;

-----------
-- Various Others.
-----------

-----------
CREATE SET TABLE HR.DimEmployee ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EmployeeKey INTEGER NOT NULL,
      ParentEmployeeKey INTEGER,
      EmployeeNationalIDAlternateKey VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      ParentEmployeeNationalIDAltKey VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      SalesTerritoryKey INTEGER,
      FirstName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      LastName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      MiddleName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      NameStyle BYTEINT CHECK ( NameStyle  IN (0 ,1 ) ) NOT NULL,
      "Title" VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      HireDate DATE FORMAT 'yyyy-mm-dd',
      BirthDate DATE FORMAT 'yyyy-mm-dd',
      LoginID VARCHAR(256) CHARACTER SET UNICODE NOT CASESPECIFIC,
      EmailAddress VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Phone VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
      MaritalStatus CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmergencyContactName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      EmergencyContactPhone VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SalariedFlag BYTEINT CHECK ( SalariedFlag  IN (0 ,1 ) ),
      Gender CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      PayFrequency BYTEINT,
      BaseRate NUMBER(18,4),
      VacationHours SMALLINT,
      SickLeaveHours SMALLINT,
      CurrentFlag BYTEINT CHECK ( CurrentFlag  IN (0 ,1 ) ) NOT NULL,
      SalesPersonFlag BYTEINT CHECK ( SalesPersonFlag  IN (0 ,1 ) ) NOT NULL,
      DepartmentName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      StartDate DATE FORMAT 'yyyy-mm-dd',
      EndDate DATE FORMAT 'yyyy-mm-dd',
      Status VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      EmployeePhoto BLOB(2097088000), 
PRIMARY KEY ( EmployeeKey ))
;

---------
CREATE MULTISET TABLE HR.EMPLOYEE_DUPE AS 
(SELECT * FROM HR.EMPLOYEE) WITH DATA;	

-----------
CREATE SET TABLE PRODUCT.DimGeography ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      GeographyKey INTEGER NOT NULL,
      City VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      StateProvinceCode VARCHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      StateProvinceName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      CountryRegionCode VARCHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      EnglishCountryRegionName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      SpanishCountryRegionName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      FrenchCountryRegionName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PostalCode VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      SalesTerritoryKey INTEGER,
      IpAddressLocator VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC, 
PRIMARY KEY ( GeographyKey ))
;

-----------
CREATE SET TABLE PRODUCT.DimAccount ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      AccountKey INTEGER NOT NULL,
      ParentAccountKey INTEGER,
      AccountCodeAlternateKey INTEGER,
      ParentAccountCodeAlternateKey INTEGER,
      AccountDescription VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      AccountType VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Operator VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      CustomMembers VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      ValueType VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      CustomMemberOptions VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC, 
PRIMARY KEY ( AccountKey ))
;

-----------
CREATE SET TABLE PRODUCT.DimDepartmentGroup ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DepartmentGroupKey INTEGER NOT NULL,
      ParentDepartmentGroupKey INTEGER,
      DepartmentGroupName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC, 
PRIMARY KEY ( DepartmentGroupKey ))
;

-----------
CREATE SET TABLE HR.FactCallCenter ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      FactCallCenterID INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      WageType VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      Shift VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      LevelOneOperators SMALLINT NOT NULL,
      LevelTwoOperators SMALLINT NOT NULL,
      TotalOperators SMALLINT NOT NULL,
      Calls INTEGER NOT NULL,
      AutomaticResponses INTEGER NOT NULL,
      Orders INTEGER NOT NULL,
      IssuesRaised SMALLINT NOT NULL,
      AverageTimePerIssue SMALLINT NOT NULL,
      ServiceGrade NUMBER NOT NULL,
      "Date" DATE FORMAT 'yyyy-mm-dd', 
PRIMARY KEY ( FactCallCenterID ))
;

-----------
CREATE SET TABLE SALES.DimPromotion ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PromotionKey INTEGER NOT NULL,
      PromotionAlternateKey INTEGER,
      EnglishPromotionName VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SpanishPromotionName VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FrenchPromotionName VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DiscountPct NUMBER,
      EnglishPromotionType VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      SpanishPromotionType VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FrenchPromotionType VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      EnglishPromotionCategory VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      SpanishPromotionCategory VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FrenchPromotionCategory VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      StartDate DATE FORMAT 'yyyy-mm-dd' NOT NULL,
      EndDate DATE FORMAT 'yyyy-mm-dd',
      MinQty INTEGER,
      MaxQty INTEGER, 
PRIMARY KEY ( PromotionKey ))
;

-----------
CREATE SET TABLE HR.DimOrganization ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      OrganizationKey INTEGER NOT NULL,
      ParentOrganizationKey INTEGER,
      PercentageOfOwnership VARCHAR(16) CHARACTER SET LATIN NOT CASESPECIFIC,
      OrganizationName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      CurrencyKey INTEGER, 
PRIMARY KEY ( OrganizationKey ))
;

-----------
CREATE SET TABLE PRODUCT.DimProduct ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ProductKey INTEGER NOT NULL,
      ProductAlternateKey VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      ProductSubcategoryKey INTEGER,
      WeightUnitMeasureCode CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      SizeUnitMeasureCode CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      EnglishProductName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SpanishProductName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      FrenchProductName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      StandardCost NUMBER(18,4),
      FinishedGoodsFlag BYTEINT CHECK ( FinishedGoodsFlag  IN (0 ,1 ) ) NOT NULL,
      Color VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SafetyStockLevel SMALLINT,
      ReorderPoint SMALLINT,
      ListPrice NUMBER(18,4),
      SIZE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      SizeRange VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Weight NUMBER,
      DaysToManufacture INTEGER,
      ProductLine CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DealerPrice NUMBER(18,4),
      "Class" CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STYLE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ModelName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LargePhoto BLOB(2097088000),
      EnglishDescription VARCHAR(400) CHARACTER SET LATIN NOT CASESPECIFIC,
      FrenchDescription VARCHAR(400) CHARACTER SET LATIN NOT CASESPECIFIC,
      ChineseDescription VARCHAR(400) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ArabicDescription VARCHAR(400) CHARACTER SET UNICODE NOT CASESPECIFIC,
      HebrewDescription VARCHAR(400) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ThaiDescription VARCHAR(400) CHARACTER SET UNICODE NOT CASESPECIFIC,
      GermanDescription VARCHAR(400) CHARACTER SET LATIN NOT CASESPECIFIC,
      JapaneseDescription VARCHAR(400) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TurkishDescription VARCHAR(400) CHARACTER SET UNICODE NOT CASESPECIFIC,
      StartDate DATE FORMAT 'yyyy-mm-dd',
      EndDate DATE FORMAT 'yyyy-mm-dd',
      Status VARCHAR(7) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'Current', 
PRIMARY KEY ( ProductKey ))
;

-----------
CREATE SET TABLE SALES.FactSurveyResponse ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SurveyResponseKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      CustomerKey INTEGER NOT NULL,
      ProductCategoryKey INTEGER NOT NULL,
      EnglishProductCategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ProductSubcategoryKey INTEGER NOT NULL,
      EnglishProductSubcategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      "Date" DATE FORMAT 'yyyy-mm-dd', 
PRIMARY KEY ( SurveyResponseKey ))
;

-----------
CREATE SET TABLE SALES.FactCurrencyRate ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CurrencyKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      AverageRate NUMBER NOT NULL,
      EndOfDayRate NUMBER NOT NULL,
      "Date" DATE FORMAT 'yyyy-mm-dd', 
PRIMARY KEY ( CurrencyKey ,DateKey ))
;

-----------
CREATE SET TABLE SALES.DimSalesTerritory ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SalesTerritoryKey INTEGER NOT NULL,
      SalesTerritoryAlternateKey INTEGER,
      SalesTerritoryRegion VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SalesTerritoryCountry VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SalesTerritoryGroup VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      SalesTerritoryImage BLOB(2097088000), 
PRIMARY KEY ( SalesTerritoryKey ))
;

-----------
CREATE SET TABLE SALES.DimReseller ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ResellerKey INTEGER NOT NULL,
      GeographyKey INTEGER,
      ResellerAlternateKey VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      Phone VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      BusinessType VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ResellerName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      NumberEmployees INTEGER,
      OrderFrequency CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      OrderMonth BYTEINT,
      FirstOrderYear INTEGER,
      LastOrderYear INTEGER,
      ProductLine VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      AddressLine1 VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
      AddressLine2 VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
      AnnualSales NUMBER(18,4),
      BankName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      MinPaymentType BYTEINT,
      MinPaymentAmount NUMBER(18,4),
      AnnualRevenue NUMBER(18,4),
      YearOpened INTEGER, 
PRIMARY KEY ( ResellerKey ))
;

-----------
CREATE SET TABLE PRODUCT.DimProductCategory ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ProductCategoryKey INTEGER NOT NULL,
      ProductCategoryAlternateKey INTEGER,
      EnglishProductCategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SpanishProductCategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      FrenchProductCategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL, 
PRIMARY KEY ( ProductCategoryKey ))
;

-----------
CREATE SET TABLE SALES.FactInternetSalesReason ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SalesOrderNumber VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SalesOrderLineNumber SMALLINT NOT NULL COMPRESS (1 ,2 ,3 ),
      SalesReasonKey INTEGER NOT NULL COMPRESS (1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ))
PRIMARY INDEX ( SalesOrderNumber );

-----------
CREATE SET TABLE HR.DimDate ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DateKey INTEGER NOT NULL,
      FullDateAlternateKey DATE FORMAT 'yyyy-mm-dd',
      DayNumberOfWeek BYTEINT,
      EnglishDayNameOfWeek VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      SpanishDayNameOfWeek VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      FrenchDayNameOfWeek VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      DayNumberOfMonth BYTEINT,
      DayNumberOfYear SMALLINT,
      WeekNumberOfYear BYTEINT,
      EnglishMonthName VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      SpanishMonthName VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      FrenchMonthName VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      MonthNumberOfYear BYTEINT,
      CalendarQuarter SMALLINT,
      CalendarYear CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      CalendarSemester SMALLINT,
      FiscalQuarter SMALLINT,
      FiscalYear CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      FiscalSemester SMALLINT, 
PRIMARY KEY ( DateKey ))
;


-----------
CREATE SET TABLE HR.FactFinance ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      FinanceKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      OrganizationKey INTEGER NOT NULL,
      DepartmentGroupKey INTEGER NOT NULL,
      ScenarioKey INTEGER NOT NULL,
      AccountKey INTEGER NOT NULL,
      Amount NUMBER NOT NULL,
      "Date" DATE FORMAT 'yyyy-mm-dd', 
PRIMARY KEY ( FinanceKey ))
;

-----------
CREATE SET TABLE PRODUCT.DimProductSubcategory ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ProductSubcategoryKey INTEGER NOT NULL,
      ProductSubcategoryAlternateKey INTEGER,
      EnglishProductSubcategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SpanishProductSubcategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      FrenchProductSubcategoryName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ProductCategoryKey INTEGER, 
PRIMARY KEY ( ProductSubcategoryKey ))
;

-----------
CREATE TABLE SALES.FactSalesQuota ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SalesQuotaKey INTEGER NOT NULL,
      EmployeeKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      CalendarYear SMALLINT NOT NULL,
      CalendarQuarter BYTEINT NOT NULL,
      SalesAmountQuota NUMBER(18,4) NOT NULL,
      "Date" DATE FORMAT 'yyyy-mm-dd', 
PRIMARY KEY ( SalesQuotaKey ))
PARTITION BY COLUMN (CALENDARYEAR);
;


-----------
CREATE SET TABLE HR.DimCurrency ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CurrencyKey INTEGER NOT NULL,
      CurrencyAlternateKey CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      CurrencyName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL, 
PRIMARY KEY ( CurrencyKey ))
;

-----------
-- Multiset Table.
-----------
CREATE MULTISET TABLE SALES.FactInternetSales ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ProductKey INTEGER NOT NULL,
      OrderDateKey INTEGER NOT NULL,
      DueDateKey INTEGER NOT NULL,
      ShipDateKey INTEGER NOT NULL,
      CustomerKey INTEGER NOT NULL,
      PromotionKey INTEGER NOT NULL,
      CurrencyKey INTEGER NOT NULL COMPRESS (6 ,19 ,100 ),
      SalesTerritoryKey INTEGER NOT NULL COMPRESS (1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ),
      SalesOrderNumber VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SalesOrderLineNumber SMALLINT NOT NULL COMPRESS (1 ,2 ,3 ),
      RevisionNumber BYTEINT NOT NULL COMPRESS 1 ,
      OrderQuantity SMALLINT NOT NULL COMPRESS 1 ,
      UnitPrice NUMBER(18,4) NOT NULL,
      ExtendedAmount NUMBER(18,4) NOT NULL,
      UnitPriceDiscountPct NUMBER NOT NULL COMPRESS 0 ,
      DiscountAmount NUMBER NOT NULL COMPRESS 0 ,
      ProductStandardCost NUMBER(18,4) NOT NULL,
      TotalProductCost NUMBER(18,4) NOT NULL,
      SalesAmount NUMBER(18,4) NOT NULL,
      TaxAmt NUMBER(18,4) NOT NULL,
      Freight NUMBER(18,4) NOT NULL,
      CarrierTrackingNumber VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      CustomerPONumber VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      OrderDate DATE FORMAT 'yyyy-mm-dd',
      DueDate DATE FORMAT 'yyyy-mm-dd',
      ShipDate DATE FORMAT 'yyyy-mm-dd')
PRIMARY INDEX ( SalesOrderNumber )
PARTITION BY EXTRACT (MONTH FROM ORDERDATE);


-----------
CREATE SET TABLE PRODUCT.DimScenario ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ScenarioKey INTEGER NOT NULL,
      ScenarioName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC, 
PRIMARY KEY ( ScenarioKey ))
;

-----------
CREATE SET TABLE SALES.DimCustomer ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CustomerKey INTEGER NOT NULL,
      GeographyKey INTEGER,
      CustomerAlternateKey VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      "Title" VARCHAR(8) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ,
      FirstName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      MiddleName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LastName VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      NameStyle BYTEINT COMPRESS 0 ,
      BirthDate DATE FORMAT 'yyyy-mm-dd',
      MaritalStatus CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('M','S'),
      Suffix VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Gender CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmailAddress VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS USING TD_SYSFNLIB.TRANSUNICODETOUTF8 DECOMPRESS USING TD_SYSFNLIB.TRANSUTF8TOUNICODE ,
      YearlyIncome NUMBER(18,4) COMPRESS (10000 ,20000 ,30000 ,40000 ,50000 ,60000 ,70000 ,80000 ,90000 ,100000 ,110000 ,120000 ,130000 ,140000 ,150000 ),
      TotalChildren BYTEINT COMPRESS (0 ,1 ,2 ),
      NumberChildrenAtHome BYTEINT COMPRESS (0 ,1 ,2 ),
      EnglishEducation VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Bachelors','Partial College','High School','Graduate Degree','Partial High School'),
      SpanishEducation VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Licenciatura','Estudios universitarios (en curso)','Educación secundaria','Estudios de postgrado','Educación secundaria (en curso)'),
      FrenchEducation VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Bac + 4','Baccalauréat','Bac + 2','Bac + 3','Niveau bac'),
      EnglishOccupation VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Professional','Skilled Manual','Management','Clerical','Manual'),
      SpanishOccupation VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Profesional','Obrero especializado','Gestión','Administrativo','Obrero'),
      FrenchOccupation VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Cadre','Technicien','Direction','Employé','Ouvrier'),
      HouseOwnerFlag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('0','1'),
      NumberCarsOwned BYTEINT COMPRESS (0 ,1 ,2 ),
      AddressLine1 VARCHAR(120) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS USING TD_SYSFNLIB.TRANSUNICODETOUTF8 DECOMPRESS USING TD_SYSFNLIB.TRANSUTF8TOUNICODE ,
      AddressLine2 VARCHAR(120) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS USING TD_SYSFNLIB.TRANSUNICODETOUTF8 DECOMPRESS USING TD_SYSFNLIB.TRANSUTF8TOUNICODE ,
      Phone VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      DateFirstPurchase DATE FORMAT 'yyyy-mm-dd',
      CommuteDistance VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('0-1 Miles','2-5 Miles','1-2 Miles','5-10 Miles','10+ Miles'), 
PRIMARY KEY ( CustomerKey ))
;

-----------
CREATE MULTISET TABLE HR.PERSON_EMPLOYMENT_PERIOD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PERSON_ID INTEGER NOT NULL,
      EMPLOYMENT_PERIOD PERIOD(DATE) FORMAT 'YYYY-MM-DD')
PRIMARY INDEX ( PERSON_ID );

-----------
CREATE MULTISET TABLE HR.ACT_COUNT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ACT_COUNT INTEGER,
      LOCATION VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( ACT_COUNT );

-----------
CREATE MULTISET TABLE HR.EMPLOYEE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EMP_ID INTEGER TITLE 'Identifier',
      EMP_NAME VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Full Name',
      EMP_PHONE VARCHAR(14) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Phone Number')
PRIMARY INDEX ( EMP_ID );

-----------
CREATE SET TABLE PRODUCT.INTERVAL_DATA_TYPE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      INTERVAL_YEAR_TYPE INTERVAL YEAR(2),
      INTERVAL_MONTH_TYPE INTERVAL MONTH(2),
      INTERVAL_YEAR2MONTH_TYPE INTERVAL YEAR(2) TO MONTH,
      INTERVAL_DAY_TYPE INTERVAL DAY(2),
      INTERVAL_DAY2HOUR_TYPE INTERVAL DAY(2) TO HOUR,
      INTERVAL_DAY2MINUTE_TYPE INTERVAL DAY(2) TO MINUTE,
      INTERVAL_DAY2SECOND_TYPE INTERVAL DAY(2) TO SECOND(6),
      INTERVAL_HOUR_TYPE INTERVAL HOUR(2),
      INTERVAL_HOUR2MINUTE_TYPE INTERVAL HOUR(2) TO MINUTE,
      INTERVAL_HOUR2SECOND_TYPE INTERVAL HOUR(2) TO SECOND(6),
      INTERVAL_MINUTE_TYPE INTERVAL MINUTE(2),
      INTERVAL_MINUTE2SECOND_TYPE INTERVAL MINUTE(3) TO SECOND(3),
      INTERVAL_SECOND_TYPE INTERVAL SECOND(2,6))
PRIMARY INDEX ( INTERVAL_YEAR_TYPE );

-----------
CREATE SET TABLE HR.EMPLOYEE_PERIOD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EMPLOYEE_NUMBER INTEGER NOT NULL,
      MANAGER_EMPLOYEE_NUMBER INTEGER,
      DEPARTMENT_NUMBER INTEGER,
      JOB_CODE INTEGER,
      LAST_NAME CHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      FIRST_NAME VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SALARY_AMOUNT DECIMAL(10,2) NOT NULL,
      BIRTHDATE DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      JOB_DURATION PERIOD(DATE) FORMAT 'YYYY-MM-DD' NOT NULL)
PRIMARY INDEX ( EMPLOYEE_NUMBER );

-----------
CREATE MULTISET TABLE HR.EMPLOYEE_PHONE_INFO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EMP_ID INTEGER TITLE 'Identifier',
      EMP_NAME VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Full Name',
      EMP_PHONE VARCHAR(14) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Phone Number',
      EMP_PHONE_TYPE VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Phone Type')
PRIMARY INDEX ( EMP_ID );

-----------
CREATE MULTISET TABLE PRODUCT.ERR_SP_LOG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ERR_CODE INTEGER,
      ERR_MSG VARCHAR(3000) CHARACTER SET LATIN NOT CASESPECIFIC,
      TS TIMESTAMP(6))
PRIMARY INDEX ( ERR_CODE );

-----------
CREATE SET TABLE HR.FLIGHTS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DESTINATION VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      SOURCE VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      COST INTEGER)
PRIMARY INDEX ( DESTINATION );

-----------
CREATE MULTISET TABLE HR.PERSON_LOGIN ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PERSON_ID INTEGER NOT NULL,
      LOGIN_DTM TIMESTAMP(6) NOT NULL)
PRIMARY INDEX ( PERSON_ID );



